source "https://rubygems.org"

gem "jekyll", ">=3.8.6"
gem "jekyll-watch", ">=2.0.0"
gem 'jekyll-autoprefixer', ">=1.0.0"
gem "jekyll-assets", ">=3.0.12"
gem "jekyll-github-metadata"
gem "liquid", ">=4.0.0"
gem "pygments.rb", ">=1.2.1"
gem "redcarpet", ">=3.1"
gem "rake", ">=12.3.0"
gem "sass",">=3.7.4"
gem "sass-globbing",">=1.1.0"
gem "uglifier",">=4.1.0"
gem "sprockets", "~> 3.7"
